server:
  port: 10086
spring:
  application:
    name: eureka-server
  cloud:
    nacos:
      server-addr: localhost:8848

eureka:
  client:
    service-url:
        defaultZone: http://localhost:10086/eureka/